# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: docker build . -t gluwa/hardhat-dev:latest
  displayName: 'Build image'



- script: |
    docker pull -a gluwa/hardhat-dev
    export version = $(docker images --format "{{.Tag}}" gluwa/hardhat-dev | grep '\d.*' | sort -r | head -n 1)
    docker login -u $(userName) -p $(pass)
    docker tag gluwa/hardhat-dev:latest gluwa/hardhat-dev:$version
    docker push gluwa/hardhat-dev:latest && docker push gluwa/hardhat-dev:$version
  displayName: 'tag and push docker images'
