# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches: 
    include:
    - refs/tags/*

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    export tag=$(git describe --tag)
    echo "Tag is: $tag"
    echo "##vso[task.setvariable variable=gitTag;]$tag" 
  displayName: 'get version tag'

- task: Docker@2
  displayName: Login to gluwa
  inputs:
    command: login
    containerRegistry: gluwa

- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: gluwa/hardhat-dev
    tags: |
      $(gitTag)
      latest
